import { ConnectedDevice, Message } from '@/types/schema';

export const initialDevices: ConnectedDevice[] = [
  {
    id: 'dev-001',
    deviceId: 'NODE-001',
    userId: 'usr-101',
    userName: 'Rahul Kumar',
    role: 'USER',
    deviceType: 'PHONE',
    latitude: 26.1201,
    longitude: 86.5902,
    battery: 78,
    status: 'ONLINE',
    locationName: 'Supaul',
    lastSeen: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T10:00:00Z',
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev-002',
    deviceId: 'NODE-002',
    userId: 'resp-201',
    userName: 'Boat Alpha',
    role: 'RESPONDER',
    deviceType: 'BOAT_GPS',
    latitude: 26.1305,
    longitude: 86.6103,
    battery: 65,
    status: 'ONLINE',
    locationName: 'Sector 2B',
    lastSeen: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T09:30:00Z',
    updatedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev-003',
    deviceId: 'NODE-003',
    userId: 'usr-102',
    userName: 'Aman Sheikh',
    role: 'USER',
    deviceType: 'PHONE',
    latitude: 26.1502,
    longitude: 86.6301,
    battery: 45,
    status: 'ONLINE',
    locationName: 'Saharsa',
    lastSeen: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T10:15:00Z',
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev-004',
    deviceId: 'NODE-004',
    userId: 'resp-202',
    userName: 'Boat Bravo',
    role: 'RESPONDER',
    deviceType: 'BOAT_GPS',
    latitude: 26.1220,
    longitude: 86.6122,
    battery: 20,
    status: 'ONLINE',
    locationName: 'Sector 3A',
    lastSeen: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T09:45:00Z',
    updatedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev-005',
    deviceId: 'NODE-005',
    userId: 'usr-103',
    userName: 'Neha Kumari',
    role: 'USER',
    deviceType: 'PHONE',
    latitude: 26.1421,
    longitude: 86.6203,
    battery: 82,
    status: 'OFFLINE',
    locationName: 'Madhepura',
    lastSeen: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev-006',
    deviceId: 'NODE-006',
    userId: 'resp-203',
    userName: 'Rescue Squad Charlie',
    role: 'RESPONDER',
    deviceType: 'PHONE',
    latitude: 26.1080,
    longitude: 86.5750,
    battery: 91,
    status: 'ONLINE',
    locationName: 'Supaul South',
    lastSeen: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T08:30:00Z',
    updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev-007',
    deviceId: 'NODE-007',
    userId: 'resp-204',
    userName: 'Medical Team 1',
    role: 'RESPONDER',
    deviceType: 'PHONE',
    latitude: 26.1150,
    longitude: 86.5850,
    battery: 58,
    status: 'ONLINE',
    locationName: 'Supaul Camp',
    lastSeen: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'dev-008',
    deviceId: 'NODE-008',
    userId: 'resp-205',
    userName: 'Boat Delta',
    role: 'RESPONDER',
    deviceType: 'BOAT_GPS',
    latitude: 26.1600,
    longitude: 86.6450,
    battery: 73,
    status: 'ONLINE',
    locationName: 'Kosi Main River',
    lastSeen: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    createdAt: '2026-09-26T07:45:00Z',
    updatedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },
];

export const initialMessages: Message[] = [
  {
    id: 'MSG-1001',
    senderId: 'NODE-001',
    senderName: 'Rahul Kumar',
    senderRole: 'USER',
    message: 'Water has entered our house and 5 people are trapped on the roof. Need evacuation urgently.',
    messageType: 'SOS',
    latitude: 26.1201,
    longitude: 86.5902,
    locationName: 'Supaul',
    severity: 'P1',
    severityReason: 'Immediate life risk: 5 people trapped on rooftop with rising floodwaters.',
    status: 'UNREAD',
    isNew: true,
    geminiAnalysis: {
      severity: 'P1',
      severityLabel: 'CRITICAL',
      confidence: 0.96,
      reason: 'Multiple people are trapped on a rooftop due to active flooding with rapid water rise.',
      casualties: 5,
      vulnerabilities: ['trapped_on_roof', 'rising_water', 'family_with_elderly'],
      urgency: 'IMMEDIATE',
      recommendedAction: 'Dispatch Rescue Boat Alpha immediately to Supaul Ward 4 for rooftop extraction.',
      analyzedAt: '2026-09-26T12:28:00Z',
    },
    createdAt: '2026-09-26T12:28:00Z',
    updatedAt: '2026-09-26T12:28:00Z',
  },
  {
    id: 'MSG-1002',
    senderId: 'NODE-002',
    senderName: 'Boat Alpha',
    senderRole: 'RESPONDER',
    message: 'Need medical kit urgently for two injured villagers rescued from Sector 2B.',
    messageType: 'RESOURCE_REQ',
    latitude: 26.1305,
    longitude: 86.6103,
    locationName: 'Sector 2B',
    severity: 'P1',
    severityReason: 'Casualties requiring acute medical intervention onboard rescue vessel.',
    status: 'UNREAD',
    isNew: true,
    geminiAnalysis: {
      severity: 'P1',
      severityLabel: 'CRITICAL',
      confidence: 0.92,
      reason: 'Rescued civilians have sustained flood injuries and require emergency first aid supplies.',
      casualties: 2,
      vulnerabilities: ['flood_trauma', 'remote_waterborne'],
      urgency: 'IMMEDIATE',
      recommendedAction: 'Direct Medical Team 1 to rendezvous with Boat Alpha at Point Sector 2B.',
      analyzedAt: '2026-09-26T12:24:00Z',
    },
    createdAt: '2026-09-26T12:24:00Z',
    updatedAt: '2026-09-26T12:24:00Z',
  },
  {
    id: 'MSG-1003',
    senderId: 'NODE-003',
    senderName: 'Aman Sheikh',
    senderRole: 'USER',
    message: 'Water level rising quickly in our street. Current level is waist deep and reaching entry gate.',
    messageType: 'REPORT',
    latitude: 26.1502,
    longitude: 86.6301,
    locationName: 'Saharsa',
    severity: 'P2',
    severityReason: 'Flood surge encroaching residential structure within next 1-2 hours.',
    status: 'UNREAD',
    isNew: false,
    geminiAnalysis: {
      severity: 'P2',
      severityLabel: 'HIGH',
      confidence: 0.89,
      reason: 'Water is waist deep and rising steadily, threatening home inundation.',
      casualties: 3,
      vulnerabilities: ['ground_floor_inundation'],
      urgency: 'HIGH',
      recommendedAction: 'Advise residents to move to upper floors and stage Boat Bravo for patrol.',
      analyzedAt: '2026-09-26T12:20:00Z',
    },
    createdAt: '2026-09-26T12:20:00Z',
    updatedAt: '2026-09-26T12:20:00Z',
  },
  {
    id: 'MSG-1004',
    senderId: 'NODE-004',
    senderName: 'Boat Bravo',
    senderRole: 'RESPONDER',
    message: 'Boat fuel low (20%). Requesting refueling point before continuing Sector 3A sweep.',
    messageType: 'RESOURCE_REQ',
    latitude: 26.1220,
    longitude: 86.6122,
    locationName: 'Sector 3A',
    severity: 'P2',
    severityReason: 'Rescue boat operational risk due to low fuel reserves.',
    status: 'ACKNOWLEDGED',
    isNew: false,
    geminiAnalysis: {
      severity: 'P2',
      severityLabel: 'HIGH',
      confidence: 0.94,
      reason: 'Operational responder boat at 20% fuel risking stranding if patrol continues without top-up.',
      casualties: 0,
      vulnerabilities: ['responder_asset_strain'],
      urgency: 'HIGH',
      recommendedAction: 'Direct Boat Bravo to Supaul Fuel Staging Depot immediately.',
      analyzedAt: '2026-09-26T12:18:00Z',
    },
    createdAt: '2026-09-26T12:18:00Z',
    updatedAt: '2026-09-26T12:18:00Z',
  },
  {
    id: 'MSG-1005',
    senderId: 'dev-005',
    senderName: 'Local Volunteer',
    senderRole: 'USER',
    message: 'Road blocked near bridge connecting Supaul to Madhepura due to fallen trees and flood debris.',
    messageType: 'REPORT',
    latitude: 26.1421,
    longitude: 86.6203,
    locationName: 'Madhepura',
    severity: 'P3',
    severityReason: 'Transit corridor obstruction without immediate threat to life.',
    status: 'IN_PROGRESS',
    isNew: false,
    geminiAnalysis: {
      severity: 'P3',
      severityLabel: 'MODERATE',
      confidence: 0.91,
      reason: 'Physical obstacle blocking logistics route; no immediate human casualties reported.',
      casualties: 0,
      vulnerabilities: ['logistics_disruption'],
      urgency: 'MEDIUM',
      recommendedAction: 'Notify Public Works & road clearing teams; re-route rescue convoys via Sector 1.',
      analyzedAt: '2026-09-26T12:15:00Z',
    },
    createdAt: '2026-09-26T12:15:00Z',
    updatedAt: '2026-09-26T12:15:00Z',
  },
  // Additional P1, P2, P3, P4 messages to achieve UI.png exact breakdown (P1: 6, P2: 8, P3: 7, P4: 3 = Total 24)
  {
    id: 'MSG-1006',
    senderId: 'usr-104',
    senderName: 'Geeta Devi',
    senderRole: 'USER',
    message: 'Drowning risk! Current swept 2 cattle and 1 elder person stranded on tree.',
    messageType: 'SOS',
    latitude: 26.1340,
    longitude: 86.6020,
    locationName: 'Supaul North',
    severity: 'P1',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-26T12:05:00Z',
    updatedAt: '2026-09-26T12:05:00Z',
  },
  {
    id: 'MSG-1007',
    senderId: 'usr-105',
    senderName: 'Rameshwar Jha',
    senderRole: 'USER',
    message: 'Pregnant woman needs emergency hospital transit. Village cut off completely by water.',
    messageType: 'SOS',
    latitude: 26.1490,
    longitude: 86.6180,
    locationName: 'Saharsa Rural',
    severity: 'P1',
    status: 'IN_PROGRESS',
    createdAt: '2026-09-26T11:50:00Z',
    updatedAt: '2026-09-26T11:50:00Z',
  },
  {
    id: 'MSG-1008',
    senderId: 'resp-203',
    senderName: 'Rescue Squad Charlie',
    senderRole: 'RESPONDER',
    message: 'Embankment breach spotted at Sector 4 km 12! Water gushing towards settlement.',
    messageType: 'REPORT',
    latitude: 26.1110,
    longitude: 86.5820,
    locationName: 'Sector 4',
    severity: 'P1',
    status: 'UNREAD',
    createdAt: '2026-09-26T11:42:00Z',
    updatedAt: '2026-09-26T11:42:00Z',
  },
  {
    id: 'MSG-1009',
    senderId: 'usr-106',
    senderName: 'Sanjay Yadav',
    senderRole: 'USER',
    message: 'Mud house collapsed on eastern side. Family of 4 evacuated to high mound but no food/dry clothes.',
    messageType: 'SOS',
    latitude: 26.1260,
    longitude: 86.5910,
    locationName: 'Supaul East',
    severity: 'P1',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-26T11:30:00Z',
    updatedAt: '2026-09-26T11:30:00Z',
  },
  // P2 messages (total 8: MSG-1003, MSG-1004 + 6 more)
  {
    id: 'MSG-1010',
    senderId: 'usr-107',
    senderName: 'Kavita Singh',
    senderRole: 'USER',
    message: 'Drinking water contaminated with muddy flood water. Need chlorine tablets urgently.',
    messageType: 'RESOURCE_REQ',
    locationName: 'Saharsa',
    severity: 'P2',
    status: 'UNREAD',
    createdAt: '2026-09-26T11:15:00Z',
    updatedAt: '2026-09-26T11:15:00Z',
  },
  {
    id: 'MSG-1011',
    senderId: 'resp-204',
    senderName: 'Medical Team 1',
    senderRole: 'RESPONDER',
    message: 'Anti-venom stock depleted at Supaul forward camp. High risk of snake bites in flooded reeds.',
    messageType: 'RESOURCE_REQ',
    locationName: 'Supaul Camp',
    severity: 'P2',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-26T11:00:00Z',
    updatedAt: '2026-09-26T11:00:00Z',
  },
  {
    id: 'MSG-1012',
    senderId: 'usr-108',
    senderName: 'Mohd. Farhan',
    senderRole: 'USER',
    message: 'Primary school shelter has 40 people with baby food shortage within 6 hours.',
    messageType: 'REPORT',
    locationName: 'Madhepura',
    severity: 'P2',
    status: 'IN_PROGRESS',
    createdAt: '2026-09-26T10:45:00Z',
    updatedAt: '2026-09-26T10:45:00Z',
  },
  {
    id: 'MSG-1013',
    senderId: 'resp-205',
    senderName: 'Boat Delta',
    senderRole: 'RESPONDER',
    message: 'Strong river current near Sandbar 3 making small boat navigation hazardous.',
    messageType: 'REPORT',
    locationName: 'Kosi Main River',
    severity: 'P2',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-26T10:30:00Z',
    updatedAt: '2026-09-26T10:30:00Z',
  },
  {
    id: 'MSG-1014',
    senderId: 'usr-109',
    senderName: 'Vikas Kumar',
    senderRole: 'USER',
    message: 'Generator diesel for local pump station about to run dry in 2 hours.',
    messageType: 'RESOURCE_REQ',
    locationName: 'Supaul',
    severity: 'P2',
    status: 'UNREAD',
    createdAt: '2026-09-26T10:15:00Z',
    updatedAt: '2026-09-26T10:15:00Z',
  },
  {
    id: 'MSG-1015',
    senderId: 'usr-110',
    senderName: 'Anita Roy',
    senderRole: 'USER',
    message: 'Elderly diabetic patient needing insulin refrigeration backup due to power grid failure.',
    messageType: 'RESOURCE_REQ',
    locationName: 'Saharsa',
    severity: 'P2',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-26T10:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
  // P3 messages (total 7: MSG-1005 + 6 more)
  {
    id: 'MSG-1016',
    senderId: 'usr-111',
    senderName: 'Brijesh Sharma',
    senderRole: 'USER',
    message: 'Cattle herd of 15 cows safely moved to embankment; will need fodder supply tomorrow.',
    messageType: 'REPORT',
    locationName: 'Supaul Rural',
    severity: 'P3',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-26T09:45:00Z',
    updatedAt: '2026-09-26T09:45:00Z',
  },
  {
    id: 'MSG-1017',
    senderId: 'usr-112',
    senderName: 'Priya Mishra',
    senderRole: 'USER',
    message: 'Water entered courtyard 4 inches, currently steady not rising.',
    messageType: 'REPORT',
    locationName: 'Madhepura',
    severity: 'P3',
    status: 'UNREAD',
    createdAt: '2026-09-26T09:30:00Z',
    updatedAt: '2026-09-26T09:30:00Z',
  },
  {
    id: 'MSG-1018',
    senderId: 'resp-201',
    senderName: 'Boat Alpha',
    senderRole: 'RESPONDER',
    message: 'Completed inspection of eastern bund; minor seepage noted and marked with flags.',
    messageType: 'REPORT',
    locationName: 'Sector 2B',
    severity: 'P3',
    status: 'RESOLVED',
    createdAt: '2026-09-26T09:15:00Z',
    updatedAt: '2026-09-26T09:15:00Z',
  },
  {
    id: 'MSG-1019',
    senderId: 'usr-113',
    senderName: 'Deepak Sah',
    senderRole: 'USER',
    message: 'Community hall open for shelter if nearby houses need evacuation later tonight.',
    messageType: 'REPORT',
    locationName: 'Saharsa',
    severity: 'P3',
    status: 'ACKNOWLEDGED',
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-26T09:00:00Z',
  },
  {
    id: 'MSG-1020',
    senderId: 'usr-114',
    senderName: 'Sunita Devi',
    senderRole: 'USER',
    message: 'Requesting tarpaulin sheets for temporary roof leakage at community shed.',
    messageType: 'RESOURCE_REQ',
    locationName: 'Supaul',
    severity: 'P3',
    status: 'UNREAD',
    createdAt: '2026-09-26T08:45:00Z',
    updatedAt: '2026-09-26T08:45:00Z',
  },
  {
    id: 'MSG-1021',
    senderId: 'usr-115',
    senderName: 'Ajay Verma',
    senderRole: 'USER',
    message: 'Mobile recharge shop offering free power charging for emergency phone nodes.',
    messageType: 'REPORT',
    locationName: 'Madhepura',
    severity: 'P3',
    status: 'RESOLVED',
    createdAt: '2026-09-26T08:30:00Z',
    updatedAt: '2026-09-26T08:30:00Z',
  },
  // P4 messages (total 3)
  {
    id: 'MSG-1022',
    senderId: 'resp-202',
    senderName: 'Boat Bravo',
    senderRole: 'RESPONDER',
    message: 'Routine radio check from Sector 3A. Mesh repeater link quality 98%.',
    messageType: 'REPORT',
    locationName: 'Sector 3A',
    severity: 'P4',
    status: 'RESOLVED',
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: '2026-09-26T08:00:00Z',
  },
  {
    id: 'MSG-1023',
    senderId: 'usr-116',
    senderName: 'Manoj Tiwari',
    senderRole: 'USER',
    message: 'Weather observation: Rain has paused for past 45 minutes in Supaul town.',
    messageType: 'REPORT',
    locationName: 'Supaul',
    severity: 'P4',
    status: 'RESOLVED',
    createdAt: '2026-09-26T07:45:00Z',
    updatedAt: '2026-09-26T07:45:00Z',
  },
  {
    id: 'MSG-1024',
    senderId: 'resp-203',
    senderName: 'Rescue Squad Charlie',
    senderRole: 'RESPONDER',
    message: 'Morning shift handover completed. All squad personnel accounted for.',
    messageType: 'REPORT',
    locationName: 'Supaul South',
    severity: 'P4',
    status: 'RESOLVED',
    createdAt: '2026-09-26T07:30:00Z',
    updatedAt: '2026-09-26T07:30:00Z',
  },
];
